### ISSUE TITLE
[Feature Request] Where is output?

### ISSUE THREAD

**Issue by cympfh** [statiolake/proconio-rs#11]
Because this is proconi"o".

For examples,

```rust
output! {
  a, b, c;
  d
}
=>
println!("{} {} {}\n{}", a, b, c, d);
```

is useful?

**Comment by statiolake** [comment]
I've been thinking about adding something like your `output!` macro in one way or another, but I have no good idea what kind of macro is effective and useful so far.

With your suggestion, it may be a little more convenient, but it doesn't seem to be much different from current `println!` macro. Also if you are required to specify more complex output format, you need `println!` macro after all. For example, consider when you need to specify the precision of floating point number. If I may add, we often required to print boolean value as `Yes` or `No`.  In such a problem you normally need to write `if` statement, so below two,
```rust
println!("{}", if b { "Yes" } else { "No" });
output!(if b { "Yes" } else { "No "});
```
are not so different I think. Again I agree that the `output!` macro makes things easier but I'm not sure it's worth adding. Fortunately `println!` is useful enough in my opinion.

It's just an idea, but to enrich output support, it would be more helpful to make a wrapper type to show values in such a typical output format. For example, add `YN(bool)` to show boolean as `Yes` / `No` or `Slice(&[T])` to show elements of slice or Vec separeted by ' ' (space). The difficulty here is that output format may slightly differ depending on problems. For example, some problems require `Yes` / `No` while others `YES` / `NO`.

In any case, ideas are always welcome. Thank you for your interest!

By the way, there is `#[fastout]` attribute to speed up output (although usually you don't have to add it, so it's not so familiar as `input!` macro). That's why `proconio` has last 'o' = output.
